### ISSUE TITLE
Correct terminal width does not seem to be properly forwarded to child processes

### ISSUE THREAD

**Issue by Hubro** [DarthSim/overmind#146]
I'm [using Python's Rich library to show log output](https://rich.readthedocs.io/en/latest/logging.html) while I'm developing. This library uses the terminal width to place certain information at the very right edge of the screen.

This works great, even in tmux, but when launched through overmind or hivemind:

![image](https://user-images.githubusercontent.com/597206/214563874-91c8459f-e5ce-43ca-bd86-a4dba00eed54.png)

I tried exporting `COLUMNS` to the correct value for my current terminal, just to see what would happen:

![image](https://user-images.githubusercontent.com/597206/214565145-997e3f38-a868-4397-af07-942299d908be.png)

This value seems to be picked up by Rich, since running the command directly still works, and the Python command in hivemind now thinks it has 123 columns to work with even though hivemind itself eats some of those. It has no effect when running the command using overmind.

It seems like the terminal size isn't being correctly forwarded to the Python process.

Should this be working? If yes, how can I troubleshoot this further?

---

Example Python application to reproduce the problem:

`pyproject.toml`:

```toml
[tool.poetry]
name = "test"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
rich = "^13.2.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
```

`test.py`:

```python
import logging
from rich.logging import RichHandler

FORMAT = "%(message)s"
logging.basicConfig(
    level="NOTSET", format=FORMAT, datefmt="[%X]", handlers=[RichHandler()]
)

log = logging.getLogger("test")
log.info("Hello, World!")
```

`Procfile`:

```Procfile
test: poetry run python test.py
```
